version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    default_reviewers:
    - asmega
    - solidgoldpig
    - elena-vi
    - emileswarts
    - tommotaylor
